# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choice_Window(object):
    def setupUi(self, Choice_Window):
        Choice_Window.setObjectName("Choice_Window")
        Choice_Window.setWindowModality(QtCore.Qt.NonModal)
        Choice_Window.resize(361, 161)
        Choice_Window.setMinimumSize(QtCore.QSize(361, 161))
        Choice_Window.setMaximumSize(QtCore.QSize(361, 161))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/choice.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Choice_Window.setWindowIcon(icon)
        Choice_Window.setStyleSheet("#Choice_Window{\n"
"background: gray;\n"
"}\n"
"\n"
"#LogFrame{\n"
"background: white;\n"
"border-radius: 50px;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #fed5ff);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #55aa7f);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Choice_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.LogFrame = QtWidgets.QFrame(self.centralwidget)
        self.LogFrame.setGeometry(QtCore.QRect(10, 10, 341, 141))
        self.LogFrame.setToolTip("")
        self.LogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogFrame.setObjectName("LogFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.LogFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777213, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bttn_admin = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.bttn_admin.setFont(font)
        self.bttn_admin.setObjectName("bttn_admin")
        self.horizontalLayout.addWidget(self.bttn_admin)
        self.bttn_user = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.bttn_user.setFont(font)
        self.bttn_user.setStyleSheet("")
        self.bttn_user.setObjectName("bttn_user")
        self.horizontalLayout.addWidget(self.bttn_user)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        Choice_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Choice_Window)
        QtCore.QMetaObject.connectSlotsByName(Choice_Window)

    def retranslateUi(self, Choice_Window):
        _translate = QtCore.QCoreApplication.translate
        Choice_Window.setWindowTitle(_translate("Choice_Window", "Выбор пользователя"))
        self.label.setText(_translate("Choice_Window", "Выберите пользователя"))
        self.bttn_admin.setText(_translate("Choice_Window", "Администратор"))
        self.bttn_user.setText(_translate("Choice_Window", "Пользователь"))
