# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_Window(object):
    def setupUi(self, User_Window):
        User_Window.setObjectName("User_Window")
        User_Window.resize(361, 161)
        User_Window.setMinimumSize(QtCore.QSize(361, 161))
        User_Window.setMaximumSize(QtCore.QSize(361, 161))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        User_Window.setWindowIcon(icon)
        User_Window.setStyleSheet("#User_Window{\n"
"background: gray;\n"
"}\n"
"\n"
"#UserFrame{\n"
"background: white;\n"
"border-radius: 50px;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #fed5ff);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #55aa7f);\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(User_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.UserFrame = QtWidgets.QFrame(self.centralwidget)
        self.UserFrame.setGeometry(QtCore.QRect(10, 10, 341, 141))
        self.UserFrame.setToolTip("")
        self.UserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserFrame.setObjectName("UserFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.UserFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 20, 205, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.edit_password = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.edit_password.setFont(font)
        self.edit_password.setInputMask("")
        self.edit_password.setMaxLength(15)
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password.setObjectName("edit_password")
        self.gridLayout.addWidget(self.edit_password, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.edit_login = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.edit_login.setFont(font)
        self.edit_login.setMaxLength(15)
        self.edit_login.setObjectName("edit_login")
        self.gridLayout.addWidget(self.edit_login, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.bttn_log = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.bttn_log.setFont(font)
        self.bttn_log.setObjectName("bttn_log")
        self.gridLayout.addWidget(self.bttn_log, 2, 1, 1, 1)
        User_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(User_Window)
        QtCore.QMetaObject.connectSlotsByName(User_Window)

    def retranslateUi(self, User_Window):
        _translate = QtCore.QCoreApplication.translate
        User_Window.setWindowTitle(_translate("User_Window", "Пользователь"))
        self.label_2.setText(_translate("User_Window", "Логин"))
        self.edit_password.setToolTip(_translate("User_Window", "<html><head/><body><p>15 символов</p></body></html>"))
        self.label.setText(_translate("User_Window", "Пароль"))
        self.edit_login.setToolTip(_translate("User_Window", "<html><head/><body><p>15 символов</p></body></html>"))
        self.bttn_log.setText(_translate("User_Window", "Войти"))
